#version 430

#define N_NOTES 1024
#define N_SAMPLES 440000

layout(local_size_x = 1, local_size_y = 1)in;

layout(std430, binding = 0)buffer InputType
{
    vec2 notes[N_SAMPLES][N_NOTES];
};

layout(std430, binding = 1)buffer ResultType
{
    vec2 postprocessedNotes[N_SAMPLES][N_NOTES];
};

void main() {
    ivec2 index = ivec2(gl_GlobalInvocationID.xy);
    
    postprocessedNotes[index.x][index.y] = notes[index.x][index.y];
}
